### ISSUE TITLE
Script does not work with nanodegrees

### ISSUE THREAD

**Issue by crypdick** [riteshpradhan/udacity-dl#10]
I am trying to download my nanodegree course materials for offline viewing, but this script does not work due to the different URL structure:

```python
~ $ udacity-dl -d . nd009
* Need to download from  http://udacity.com/wiki/nd009/downloads
* Collecting downloadable content from http://udacity.com/wiki/nd009/downloads
Traceback (most recent call last):
  File "/usr/local/bin/udacity-dl", line 11, in <module>
    load_entry_point('udacity-dl==1.2.2', 'console_scripts', 'udacity-dl')()
  File "/usr/local/lib/python2.7/dist-packages/udacitydl/udacitydl.py", line 154, in main
    d.download_course(cn, dest_dir=args.dest_dir)
  File "/usr/local/lib/python2.7/dist-packages/udacitydl/udacitydl.py", line 111, in download_course
    resource_dict = self.get_downloadable_content(download_url)
  File "/usr/local/lib/python2.7/dist-packages/udacitydl/udacitydl.py", line 40, in get_downloadable_content
    vidpage = self.browser.open(course_url)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found
```

In this case, my nanodegree url is `https://classroom.udacity.com/nanodegrees/nd009/[...]`.

P.S. I am aware that the nanodegree has a panel to download all the course lectures as a .zip file, but the archive has not been updated as they've changed/added videos so many are missing.

**Comment by tkwon** [comment]
+1
